env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  -  
    binary: yamlfmt
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  -
    builds:
      - yamlfmt
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  -  
    vendor: UltiRequiem- 
    homepage: "https://github.com/UltiRequiem"
    maintainer: "Eliaz Bobadilla <eliaz.bobadilla@gmail.com>"
    description: "Easily format yaml files on terminal or your editor"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - goarm: 6
    tap:  
      owner: UltiRequiem
      name: homebrew-tap
    commit_author:
      name: "Eliaz Bobadilla"  
      email: "eliaz.bobadilla@gmail.com"
      homepage: "https://github/UltiRequiem"
    description: "Easily format yaml files on terminal or your editor"

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
