name: Test & Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        go: ["1.17"]
    name: Go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Download dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./pkg/... -v
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go build
